version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - echo Preparing for build
  build:
    commands:
      - echo Building backend
      - cd backend
      - echo Building frontend
      - cd ../frontend
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - backend/**/*
    - frontend/**/*
    - appspec.yml
    - scripts/**/*

cache:
  paths:
    - "node_modules/**/*"
